metadata.format.version = "1.1"

[versions]

# CompileOnly dependencies
paper = "1.21.10-R0.1-SNAPSHOT"
minecraft = "1.21.10"

fabric-api = "0.135.0+1.21.10"
fabric-loader = "0.18.3"

adventure = "4.25.0"
adventurefabric = "6.8.0"

configurate = "4.2.0"

# Gradle Plugins
shadow = "9.3.0"
runtask= "3.0.2"

[libraries]

# Compile Only Dependencies
paper-api = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }

minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }
fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric-api" }
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric-loader" }
luckopermissionsapi = { group = "me.lucko", name = "fabric-permissions-api", version = "0.5.0" }

adventure-api = { group = "net.kyori", name = "adventure-api", version.ref = "adventure" }
adventure-minimessage = { group = "net.kyori", name = "adventure-text-minimessage", version.ref = "adventure" }
adventure-platform-fabric = { group = "net.kyori", name = "adventure-platform-fabric", version.ref = "adventurefabric" }

slf4j = "org.slf4j:slf4j-api:2.0.17"

configurate-api = { module = "org.spongepowered:configurate-core", version.ref = "configurate" }
configurate-hocon = { module = "org.spongepowered:configurate-hocon", version.ref = "configurate" }

annotations = "org.jetbrains:annotations:26.0.2-1"

[plugins]

shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
runpaper = { id = "xyz.jpenilla.run-paper", version.ref = "runtask" }
pluginyml-paper = { id = "net.minecrell.plugin-yml.paper", version = "0.6.0" }
idea-ext = { id = "org.jetbrains.gradle.plugin.idea-ext", version = "1.3" }